### ISSUE TITLE
Can't create 'any' matcher for String or Java interface

### ISSUE THREAD

**Issue by fishb6nes** [MarkusAmshove/Kluent#32] opened 2017-03-25 12:27 UTC
Heya, I am attempting to 'any' match a String and an interface from a Java library, but contrary to Double, I can't seem to get them to work. Is there a different approach I should take for non-primitives?

```
interface Foo {

}

println(Double::class.toString())         // prints "class kotlin.Double" 
println(Double::class.java.toString())    // prints "double"
println(any(Double::class))               // prints "0.0"

println(String::class.toString())         // prints "class kotlin.String"
println(String::class.java.toString())    // prints "class java.lang.String"
println(any(String::class))               // throws "java.lang.IllegalStateException: any(kClass.javaObjectType) must not be null"

println(Foo::class.toString())            // prints "class Foo"
println(Foo::class.java.toString())       // prints "interface Foo"
println(any(Foo::class))                  // throws "java.lang.IllegalStateException: any(kClass.javaObjectType) must not be null"
```

I'm using Spek 1.1.0-beta4 with Kluent 1.16. The Mockito version that was pulled in is 2.1.0 (explicitly depending on the latest version doesn't seem to change anything).

Thank you

**Comment by MarkusAmshove** [comment] 2017-03-25 16:45
Hello @fishb6nes ,

I think this is (almost) expected behavior.

If I use the following Java code:

```java
import static org.mockito.Mockito.*;

public class Test {
    public static void main(String[] args){
        Foo mock = mock(Foo.class);
        when(mock.getText()).thenReturn(any());
        System.out.println(mock.getText());
    }
}

public interface Foo {
    String getText();
}
```

I get the following exception:

```
Exception in thread "main" org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
0 matchers expected, 1 recorded:
-> at org.Test.main(Test.java:8)

This exception may occur if matchers are combined with raw values:
//incorrect:
someMethod(anyObject(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
//correct:
someMethod(anyObject(), eq("String by matcher"));

For more info see javadoc for Matchers class.

at org.Test.main(Test.java:9)
```

Looking at their [docs](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/ArgumentMatchers.java#L95) it seems like you aren't supposed to return a matcher. 

When trying to return `anyDouble()` I get the same exception.

I think we rather need a way to also trigger the "correct exception" from Mockito

**Comment by MarkusAmshove** [comment] 2017-03-25 16:57
Another hint is in their [Reporter](https://github.com/mockito/mockito/blob/806699853a2b6af9306d8e9984568c3d206289aa/src/main/java/org/mockito/internal/exceptions/Reporter.java#L511)

**Comment by fishb6nes** [comment] 2017-03-25 17:50
Thank you for the detailed response.

Hm, so how would we go about stubbing methods that take non-primitive parameters if `any(NonPrimitiveClass::class)` throws an exception?

```
interface Foo {
    fun test(foo: Foo): String
}

describe("Foo") {
    val mockFoo = mock(Foo::class)
    given("it returns 'Test'") {
        When calling mockFoo.test(any(Foo::class)) itReturns "Test"   // throws "java.lang.IllegalStateException: any(kClass.javaObjectType) must not be null"
    }
}
```

**Comment by MarkusAmshove** [comment] 2017-03-25 18:53
I just tested it and you're right, it doesn't work (we're missing tests for this)

I tested [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) and their `any()` method is working. From a quick look they heavily use [reflection](https://github.com/nhaarman/mockito-kotlin/tree/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/createinstance) to create an instance.

The problem seems to be that Mockito often returns null on their `any()` method, whereas our return type is not nullable. Catching that exception isn't possible because it occurs in the return.

I do see 2 possible solutions:

a) implement our own way to create such objects
b) depend on mockito-kotlin instead of Mockito and wrap mockito-kotlin into the fluent stuff.

I think I prefer the 2nd option because it is also a good opportunity to complete the rest of stubbing/mocking which isn't in Kluent yet :-)

**Comment by fishb6nes** [comment] 2017-03-25 21:20
I agree, lets not reinvent the wheel.

I'm not too familiar with this whole 'infix' function thingymebob, but let me know if there's anything I can contribute to. Otherwise I will patiently await any further developments.

**Comment by MarkusAmshove** [comment] 2017-03-27 06:16
I'll get on to this this weekend ;-) Thank you for finding this problem in the first place!

**Comment by MarkusAmshove** [comment] 2017-03-31 16:17
Could you have a look at the PR and the one reviewed commit if this would handle this case?

@fishb6nes

**Comment by fishb6nes** [comment] 2017-04-01 11:40
Awesome, matching classes appears to work like a charm locally 👍

**Comment by MarkusAmshove** [comment] 2017-04-02 15:52
version 1.17 has just been released and contains the fix for this issue :-)

thanks again!

**Closed by MarkusAmshove** 2017-04-02 15:52 UTC
